name: final_project
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  dio: ^5.4.0
  dartz: ^0.10.1
  firebase_auth: ^4.15.0
  firebase_core: ^2.24.0
  material_design_icons_flutter: ^7.0.7296
  flutter_phosphor_icons: ^0.0.1+6
  shared_preferences: ^2.2.2
  camera: ^0.10.5+6
  provider: ^6.1.1
  cloud_firestore: ^4.14.0
  flutter_bloc: ^8.1.3
  curved_navigation_bar: ^1.0.3
  awesome_dialog: ^3.2.0
  location: ^5.0.0
  google_maps_flutter: ^2.5.3
  flutter_local_notifications: ^17.1.0
  package_info_plus: ^5.0.1
  device_apps: ^2.2.0
  flutter_overlay: ^1.0.0
  geolocator: ^11.1.0
  geocoding: ^3.0.0
  flutter_polyline_points: ^2.0.0
  get: ^4.6.6
  audioplayers: ^5.2.1
  pie_chart: ^5.4.0
  image_picker: ^1.1.2
  firebase_storage: ^11.6.9
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  animate_do: ^3.1.2
  google_fonts: ^6.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/photo_splash.jpg
    - assets/images/location_icon.png
    - assets/images/default_profile.png
    - assets/images/cameraa.png
    - assets/drowsy_alarm.mp3
    - assets/seatbelt_alarm.mp3
